// Generated by gencpp from file motion_estimation/configMotionEstimationActionGoal.msg
// DO NOT EDIT!


#ifndef MOTION_ESTIMATION_MESSAGE_CONFIGMOTIONESTIMATIONACTIONGOAL_H
#define MOTION_ESTIMATION_MESSAGE_CONFIGMOTIONESTIMATIONACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <motion_estimation/configMotionEstimationGoal.h>

namespace motion_estimation
{
template <class ContainerAllocator>
struct configMotionEstimationActionGoal_
{
  typedef configMotionEstimationActionGoal_<ContainerAllocator> Type;

  configMotionEstimationActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  configMotionEstimationActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::motion_estimation::configMotionEstimationGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct configMotionEstimationActionGoal_

typedef ::motion_estimation::configMotionEstimationActionGoal_<std::allocator<void> > configMotionEstimationActionGoal;

typedef boost::shared_ptr< ::motion_estimation::configMotionEstimationActionGoal > configMotionEstimationActionGoalPtr;
typedef boost::shared_ptr< ::motion_estimation::configMotionEstimationActionGoal const> configMotionEstimationActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_estimation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'motion_estimation': ['/home/ryan/GitHub_WorkSpace/dataGeneration/devel/share/motion_estimation/msg'], 'shared_files': ['/home/ryan/GitHub_WorkSpace/dataGeneration/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a52f1bc3d76fd049576ed153ca190dd";
  }

  static const char* value(const ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a52f1bc3d76fd04ULL;
  static const uint64_t static_value2 = 0x9576ed153ca190ddULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_estimation/configMotionEstimationActionGoal";
  }

  static const char* value(const ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
configMotionEstimationGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: motion_estimation/configMotionEstimationGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/Float64[] QRow_one\n\
std_msgs/Float64[] QRow_two\n\
std_msgs/Float64[] QRow_three\n\
std_msgs/Float64[] QRow_four\n\
shared_files/TransformNames tname\n\
shared_files/TopicNames topname\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
================================================================================\n\
MSG: shared_files/TransformNames\n\
std_msgs/String ID\n\
std_msgs/String world_frame\n\
std_msgs/String cm\n\
std_msgs/String left\n\
std_msgs/String right\n\
std_msgs/String left_cv\n\
std_msgs/String right_cv\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: shared_files/TopicNames\n\
std_msgs/String RelativeCloudTopic\n\
std_msgs/String MatchesTopic\n\
std_msgs/String NoisyEstimationTopic\n\
std_msgs/String OriginalTopic\n\
std_msgs/String RectifiedEstimationTopic\n\
std_msgs/String MapTopic\n\
";
  }

  static const char* value(const ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct configMotionEstimationActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_estimation::configMotionEstimationActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::motion_estimation::configMotionEstimationGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_ESTIMATION_MESSAGE_CONFIGMOTIONESTIMATIONACTIONGOAL_H
