// Generated by gencpp from file shared_files/MatchFrame.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_MATCHFRAME_H
#define SHARED_FILES_MESSAGE_MATCHFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <shared_files/MatchingPoints.h>
#include <std_msgs/Int32.h>

namespace shared_files
{
template <class ContainerAllocator>
struct MatchFrame_
{
  typedef MatchFrame_<ContainerAllocator> Type;

  MatchFrame_()
    : Frame()
    , frame_id()  {
    }
  MatchFrame_(const ContainerAllocator& _alloc)
    : Frame(_alloc)
    , frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::shared_files::MatchingPoints_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::shared_files::MatchingPoints_<ContainerAllocator> >::other >  _Frame_type;
  _Frame_type Frame;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _frame_id_type;
  _frame_id_type frame_id;




  typedef boost::shared_ptr< ::shared_files::MatchFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_files::MatchFrame_<ContainerAllocator> const> ConstPtr;

}; // struct MatchFrame_

typedef ::shared_files::MatchFrame_<std::allocator<void> > MatchFrame;

typedef boost::shared_ptr< ::shared_files::MatchFrame > MatchFramePtr;
typedef boost::shared_ptr< ::shared_files::MatchFrame const> MatchFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_files::MatchFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_files::MatchFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'shared_files': ['/home/ryan/GitHub_WorkSpace/dataGeneration/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::MatchFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::MatchFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::MatchFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::MatchFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::MatchFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::MatchFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_files::MatchFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8eda00529b8ce2ece82093576c44798";
  }

  static const char* value(const ::shared_files::MatchFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8eda00529b8ce2eULL;
  static const uint64_t static_value2 = 0xce82093576c44798ULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_files::MatchFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/MatchFrame";
  }

  static const char* value(const ::shared_files::MatchFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_files::MatchFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/MatchingPoints[] Frame\n\
std_msgs/Int32 frame_id\n\
\n\
================================================================================\n\
MSG: shared_files/MatchingPoints\n\
shared_files/PixelMatch Rectified\n\
shared_files/PixelMatch Noise\n\
std_msgs/Int32 NumberID\n\
\n\
================================================================================\n\
MSG: shared_files/PixelMatch\n\
std_msgs/Float32 u\n\
std_msgs/Float32 v\n\
std_msgs/Float32 Disparity\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::shared_files::MatchFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_files::MatchFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Frame);
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MatchFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_files::MatchFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_files::MatchFrame_<ContainerAllocator>& v)
  {
    s << indent << "Frame[]" << std::endl;
    for (size_t i = 0; i < v.Frame.size(); ++i)
    {
      s << indent << "  Frame[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::shared_files::MatchingPoints_<ContainerAllocator> >::stream(s, indent + "    ", v.Frame[i]);
    }
    s << indent << "frame_id: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_FILES_MESSAGE_MATCHFRAME_H
