// Generated by gencpp from file shared_files/PixelMatch.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_PIXELMATCH_H
#define SHARED_FILES_MESSAGE_PIXELMATCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace shared_files
{
template <class ContainerAllocator>
struct PixelMatch_
{
  typedef PixelMatch_<ContainerAllocator> Type;

  PixelMatch_()
    : u()
    , v()
    , Disparity()  {
    }
  PixelMatch_(const ContainerAllocator& _alloc)
    : u(_alloc)
    , v(_alloc)
    , Disparity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _u_type;
  _u_type u;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _v_type;
  _v_type v;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _Disparity_type;
  _Disparity_type Disparity;




  typedef boost::shared_ptr< ::shared_files::PixelMatch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_files::PixelMatch_<ContainerAllocator> const> ConstPtr;

}; // struct PixelMatch_

typedef ::shared_files::PixelMatch_<std::allocator<void> > PixelMatch;

typedef boost::shared_ptr< ::shared_files::PixelMatch > PixelMatchPtr;
typedef boost::shared_ptr< ::shared_files::PixelMatch const> PixelMatchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_files::PixelMatch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_files::PixelMatch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'shared_files': ['/home/ryan/GitHub_WorkSpace/dataGeneration/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::PixelMatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::PixelMatch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::PixelMatch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::PixelMatch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::PixelMatch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::PixelMatch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_files::PixelMatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc4630c4c968b99ca3b0661c0dcd1ff2";
  }

  static const char* value(const ::shared_files::PixelMatch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc4630c4c968b99cULL;
  static const uint64_t static_value2 = 0xa3b0661c0dcd1ff2ULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_files::PixelMatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/PixelMatch";
  }

  static const char* value(const ::shared_files::PixelMatch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_files::PixelMatch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 u\n\
std_msgs/Float32 v\n\
std_msgs/Float32 Disparity\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::shared_files::PixelMatch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_files::PixelMatch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.Disparity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PixelMatch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_files::PixelMatch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_files::PixelMatch_<ContainerAllocator>& v)
  {
    s << indent << "u: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.v);
    s << indent << "Disparity: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.Disparity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_FILES_MESSAGE_PIXELMATCH_H
