# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from shared_files/FrameEstimate.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import shared_files.msg
import geometry_msgs.msg
import std_msgs.msg

class FrameEstimate(genpy.Message):
  _md5sum = "a58822c36a5a09a9ff3af0866ae1f737"
  _type = "shared_files/FrameEstimate"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """shared_files/PointSet[] Points
std_msgs/Int32 FrameNum

================================================================================
MSG: shared_files/PointSet
shared_files/PointEstimate RectifiedPoint
shared_files/PointEstimate NoisyPoint
std_msgs/Int32 PointID

================================================================================
MSG: shared_files/PointEstimate
geometry_msgs/Point32 Estimate
std_msgs/Float32[] CovRowOne
std_msgs/Float32[] CovRowTwo
std_msgs/Float32[] CovRowThree

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: std_msgs/Float32
float32 data
================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['Points','FrameNum']
  _slot_types = ['shared_files/PointSet[]','std_msgs/Int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Points,FrameNum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FrameEstimate, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Points is None:
        self.Points = []
      if self.FrameNum is None:
        self.FrameNum = std_msgs.msg.Int32()
    else:
      self.Points = []
      self.FrameNum = std_msgs.msg.Int32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.Points)
      buff.write(_struct_I.pack(length))
      for val1 in self.Points:
        _v1 = val1.RectifiedPoint
        _v2 = _v1.Estimate
        _x = _v2
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        length = len(_v1.CovRowOne)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.CovRowOne:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v1.CovRowTwo)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.CovRowTwo:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v1.CovRowThree)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.CovRowThree:
          buff.write(_struct_f.pack(val3.data))
        _v3 = val1.NoisyPoint
        _v4 = _v3.Estimate
        _x = _v4
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        length = len(_v3.CovRowOne)
        buff.write(_struct_I.pack(length))
        for val3 in _v3.CovRowOne:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v3.CovRowTwo)
        buff.write(_struct_I.pack(length))
        for val3 in _v3.CovRowTwo:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v3.CovRowThree)
        buff.write(_struct_I.pack(length))
        for val3 in _v3.CovRowThree:
          buff.write(_struct_f.pack(val3.data))
        _v5 = val1.PointID
        buff.write(_struct_i.pack(_v5.data))
      buff.write(_struct_i.pack(self.FrameNum.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.Points is None:
        self.Points = None
      if self.FrameNum is None:
        self.FrameNum = std_msgs.msg.Int32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Points = []
      for i in range(0, length):
        val1 = shared_files.msg.PointSet()
        _v6 = val1.RectifiedPoint
        _v7 = _v6.Estimate
        _x = _v7
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v6.CovRowOne = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v6.CovRowOne.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v6.CovRowTwo = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v6.CovRowTwo.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v6.CovRowThree = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v6.CovRowThree.append(val3)
        _v8 = val1.NoisyPoint
        _v9 = _v8.Estimate
        _x = _v9
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v8.CovRowOne = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v8.CovRowOne.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v8.CovRowTwo = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v8.CovRowTwo.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v8.CovRowThree = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v8.CovRowThree.append(val3)
        _v10 = val1.PointID
        start = end
        end += 4
        (_v10.data,) = _struct_i.unpack(str[start:end])
        self.Points.append(val1)
      start = end
      end += 4
      (self.FrameNum.data,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.Points)
      buff.write(_struct_I.pack(length))
      for val1 in self.Points:
        _v11 = val1.RectifiedPoint
        _v12 = _v11.Estimate
        _x = _v12
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        length = len(_v11.CovRowOne)
        buff.write(_struct_I.pack(length))
        for val3 in _v11.CovRowOne:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v11.CovRowTwo)
        buff.write(_struct_I.pack(length))
        for val3 in _v11.CovRowTwo:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v11.CovRowThree)
        buff.write(_struct_I.pack(length))
        for val3 in _v11.CovRowThree:
          buff.write(_struct_f.pack(val3.data))
        _v13 = val1.NoisyPoint
        _v14 = _v13.Estimate
        _x = _v14
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        length = len(_v13.CovRowOne)
        buff.write(_struct_I.pack(length))
        for val3 in _v13.CovRowOne:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v13.CovRowTwo)
        buff.write(_struct_I.pack(length))
        for val3 in _v13.CovRowTwo:
          buff.write(_struct_f.pack(val3.data))
        length = len(_v13.CovRowThree)
        buff.write(_struct_I.pack(length))
        for val3 in _v13.CovRowThree:
          buff.write(_struct_f.pack(val3.data))
        _v15 = val1.PointID
        buff.write(_struct_i.pack(_v15.data))
      buff.write(_struct_i.pack(self.FrameNum.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.Points is None:
        self.Points = None
      if self.FrameNum is None:
        self.FrameNum = std_msgs.msg.Int32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.Points = []
      for i in range(0, length):
        val1 = shared_files.msg.PointSet()
        _v16 = val1.RectifiedPoint
        _v17 = _v16.Estimate
        _x = _v17
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v16.CovRowOne = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v16.CovRowOne.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v16.CovRowTwo = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v16.CovRowTwo.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v16.CovRowThree = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v16.CovRowThree.append(val3)
        _v18 = val1.NoisyPoint
        _v19 = _v18.Estimate
        _x = _v19
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v18.CovRowOne = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v18.CovRowOne.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v18.CovRowTwo = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v18.CovRowTwo.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v18.CovRowThree = []
        for i in range(0, length):
          val3 = std_msgs.msg.Float32()
          start = end
          end += 4
          (val3.data,) = _struct_f.unpack(str[start:end])
          _v18.CovRowThree.append(val3)
        _v20 = val1.PointID
        start = end
        end += 4
        (_v20.data,) = _struct_i.unpack(str[start:end])
        self.Points.append(val1)
      start = end
      end += 4
      (self.FrameNum.data,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_3f = struct.Struct("<3f")
_struct_f = struct.Struct("<f")
