# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from shared_files/RelativePoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class RelativePoint(genpy.Message):
  _md5sum = "024347b0198bd44300804769f09d3b6b"
  _type = "shared_files/RelativePoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point coord
std_msgs/Int32 identification

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['coord','identification']
  _slot_types = ['geometry_msgs/Point','std_msgs/Int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       coord,identification

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RelativePoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.coord is None:
        self.coord = geometry_msgs.msg.Point()
      if self.identification is None:
        self.identification = std_msgs.msg.Int32()
    else:
      self.coord = geometry_msgs.msg.Point()
      self.identification = std_msgs.msg.Int32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3di.pack(_x.coord.x, _x.coord.y, _x.coord.z, _x.identification.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.coord is None:
        self.coord = geometry_msgs.msg.Point()
      if self.identification is None:
        self.identification = std_msgs.msg.Int32()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.coord.x, _x.coord.y, _x.coord.z, _x.identification.data,) = _struct_3di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3di.pack(_x.coord.x, _x.coord.y, _x.coord.z, _x.identification.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.coord is None:
        self.coord = geometry_msgs.msg.Point()
      if self.identification is None:
        self.identification = std_msgs.msg.Int32()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.coord.x, _x.coord.y, _x.coord.z, _x.identification.data,) = _struct_3di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3di = struct.Struct("<3di")
