(cl:defpackage simulator-msg
  (:use )
  (:export
   "<GENDATAGOAL>"
   "GENDATAGOAL"
   "<GENDATAFEEDBACK>"
   "GENDATAFEEDBACK"
   "<GENDATAACTIONFEEDBACK>"
   "GENDATAACTIONFEEDBACK"
   "<GENDATARESULT>"
   "GENDATARESULT"
   "<GENDATAACTIONRESULT>"
   "GENDATAACTIONRESULT"
   "<GENDATAACTIONGOAL>"
   "GENDATAACTIONGOAL"
   "<GENDATAACTION>"
   "GENDATAACTION"
  ))

