; Auto-generated. Do not edit!


(cl:in-package simulator-msg)


;//! \htmlinclude newSimulationResult.msg.html

(cl:defclass <newSimulationResult> (roslisp-msg-protocol:ros-message)
  ((foo
    :reader foo
    :initarg :foo
    :type std_msgs-msg:Empty
    :initform (cl:make-instance 'std_msgs-msg:Empty)))
)

(cl:defclass newSimulationResult (<newSimulationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <newSimulationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'newSimulationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name simulator-msg:<newSimulationResult> is deprecated: use simulator-msg:newSimulationResult instead.")))

(cl:ensure-generic-function 'foo-val :lambda-list '(m))
(cl:defmethod foo-val ((m <newSimulationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader simulator-msg:foo-val is deprecated.  Use simulator-msg:foo instead.")
  (foo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <newSimulationResult>) ostream)
  "Serializes a message object of type '<newSimulationResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'foo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <newSimulationResult>) istream)
  "Deserializes a message object of type '<newSimulationResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'foo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<newSimulationResult>)))
  "Returns string type for a message object of type '<newSimulationResult>"
  "simulator/newSimulationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'newSimulationResult)))
  "Returns string type for a message object of type 'newSimulationResult"
  "simulator/newSimulationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<newSimulationResult>)))
  "Returns md5sum for a message object of type '<newSimulationResult>"
  "256e907a74585c86051805b50c5f7dc8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'newSimulationResult)))
  "Returns md5sum for a message object of type 'newSimulationResult"
  "256e907a74585c86051805b50c5f7dc8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<newSimulationResult>)))
  "Returns full string definition for message of type '<newSimulationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Empty foo~%~%================================================================================~%MSG: std_msgs/Empty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'newSimulationResult)))
  "Returns full string definition for message of type 'newSimulationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Empty foo~%~%================================================================================~%MSG: std_msgs/Empty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <newSimulationResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'foo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <newSimulationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'newSimulationResult
    (cl:cons ':foo (foo msg))
))
