(cl:defpackage shared_files-msg
  (:use )
  (:export
   "<MATCHFRAME>"
   "MATCHFRAME"
   "<TRANSFORMNAMES>"
   "TRANSFORMNAMES"
   "<SETTINGSTRANSFORM>"
   "SETTINGSTRANSFORM"
   "<RELATIVEPOINT>"
   "RELATIVEPOINT"
   "<MATCHINGPOINTS>"
   "MATCHINGPOINTS"
   "<TOPICNAMES>"
   "TOPICNAMES"
   "<POINTESTIMATE>"
   "POINTESTIMATE"
   "<PIXELMATCH>"
   "PIXELMATCH"
   "<FRAMEESTIMATE>"
   "FRAMEESTIMATE"
   "<POINTSET>"
   "POINTSET"
   "<RELATIVEFRAME>"
   "RELATIVEFRAME"
  ))

