(cl:in-package shared_files-msg)
(cl:export '(RELATIVECLOUDTOPIC-VAL
          RELATIVECLOUDTOPIC
          MATCHESTOPIC-VAL
          MATCHESTOPIC
          NOISYESTIMATIONTOPIC-VAL
          NOISYESTIMATIONTOPIC
          ORIGINALTOPIC-VAL
          ORIGINALTOPIC
          RECTIFIEDESTIMATIONTOPIC-VAL
          RECTIFIEDESTIMATIONTOPIC
          MAPTOPIC-VAL
          MAPTOPIC
))