(cl:defpackage motion_estimation-msg
  (:use )
  (:export
   "<CONFIGMOTIONESTIMATIONGOAL>"
   "CONFIGMOTIONESTIMATIONGOAL"
   "<CONFIGMOTIONESTIMATIONACTION>"
   "CONFIGMOTIONESTIMATIONACTION"
   "<CONFIGMOTIONESTIMATIONACTIONGOAL>"
   "CONFIGMOTIONESTIMATIONACTIONGOAL"
   "<CONFIGMOTIONESTIMATIONFEEDBACK>"
   "CONFIGMOTIONESTIMATIONFEEDBACK"
   "<CONFIGMOTIONESTIMATIONACTIONFEEDBACK>"
   "CONFIGMOTIONESTIMATIONACTIONFEEDBACK"
   "<CONFIGMOTIONESTIMATIONRESULT>"
   "CONFIGMOTIONESTIMATIONRESULT"
   "<CONFIGMOTIONESTIMATIONACTIONRESULT>"
   "CONFIGMOTIONESTIMATIONACTIONRESULT"
  ))

