; Auto-generated. Do not edit!


(cl:in-package motion_estimation-msg)


;//! \htmlinclude configMotionEstimationResult.msg.html

(cl:defclass <configMotionEstimationResult> (roslisp-msg-protocol:ros-message)
  ((foo
    :reader foo
    :initarg :foo
    :type std_msgs-msg:Empty
    :initform (cl:make-instance 'std_msgs-msg:Empty)))
)

(cl:defclass configMotionEstimationResult (<configMotionEstimationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <configMotionEstimationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'configMotionEstimationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motion_estimation-msg:<configMotionEstimationResult> is deprecated: use motion_estimation-msg:configMotionEstimationResult instead.")))

(cl:ensure-generic-function 'foo-val :lambda-list '(m))
(cl:defmethod foo-val ((m <configMotionEstimationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motion_estimation-msg:foo-val is deprecated.  Use motion_estimation-msg:foo instead.")
  (foo m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <configMotionEstimationResult>) ostream)
  "Serializes a message object of type '<configMotionEstimationResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'foo) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <configMotionEstimationResult>) istream)
  "Deserializes a message object of type '<configMotionEstimationResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'foo) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<configMotionEstimationResult>)))
  "Returns string type for a message object of type '<configMotionEstimationResult>"
  "motion_estimation/configMotionEstimationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'configMotionEstimationResult)))
  "Returns string type for a message object of type 'configMotionEstimationResult"
  "motion_estimation/configMotionEstimationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<configMotionEstimationResult>)))
  "Returns md5sum for a message object of type '<configMotionEstimationResult>"
  "256e907a74585c86051805b50c5f7dc8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'configMotionEstimationResult)))
  "Returns md5sum for a message object of type 'configMotionEstimationResult"
  "256e907a74585c86051805b50c5f7dc8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<configMotionEstimationResult>)))
  "Returns full string definition for message of type '<configMotionEstimationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Empty foo~%~%================================================================================~%MSG: std_msgs/Empty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'configMotionEstimationResult)))
  "Returns full string definition for message of type 'configMotionEstimationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Empty foo~%~%================================================================================~%MSG: std_msgs/Empty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <configMotionEstimationResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'foo))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <configMotionEstimationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'configMotionEstimationResult
    (cl:cons ':foo (foo msg))
))
