(cl:defpackage blackbox_matcher-msg
  (:use )
  (:export
   "<CONFIGCAMERAACTIONRESULT>"
   "CONFIGCAMERAACTIONRESULT"
   "<CONFIGCAMERAACTIONGOAL>"
   "CONFIGCAMERAACTIONGOAL"
   "<CONFIGCAMERAACTIONFEEDBACK>"
   "CONFIGCAMERAACTIONFEEDBACK"
   "<CONFIGCAMERAFEEDBACK>"
   "CONFIGCAMERAFEEDBACK"
   "<CONFIGCAMERAGOAL>"
   "CONFIGCAMERAGOAL"
   "<CONFIGCAMERAACTION>"
   "CONFIGCAMERAACTION"
   "<CONFIGCAMERARESULT>"
   "CONFIGCAMERARESULT"
  ))

